sudo: false
language: ruby
rvm:
- 2.3.0
branches:
  only:
  - master
install:
- bundle install --path _vendor/bundle
cache: bundler
script: bundle exec jekyll build
after_success:
- "./deploy.sh setup"
- "./deploy.sh deploy"
env:
  global:
    secure: CYerRbpkE5Z0FboeP64tqTj7i+L3BxaQMshrhu5UN7golW4X2dZrsZg0/MkoSsmi0rsSNfvykUZ8HmyOwiZFrLJLbfdJhuszq1semjn6HaNypHdf9CoJ4WZUjmBzhlDKNYd3yLhk9+28hfxHYCbaQ0jyjrBVn7dh0abyAeWT8Nsfglk05IwyXEFt+Oh32yW2BCUpd/oPALNQic08OuPBB0cJuGDRhd2JW7lyNsIu+TKewwOt7Q7uc7qqnR5hwFOI2H+Vnf/iPKcvd56Mxukyrhxiuxjvuv8vR1GgI5LCNXBPe8G2/v35tDrScR6JrhY/5BsIoFPpKxWaxwxrdUsvC1M2cGnn7qB/QrExBdZ4XcA9FuWgxcXM3JpLw6gQIlwqUsWfdMjPTcOt8IXLu3LzjSJl9s6l887aSL6u/RY4s31vemauhyeccqQSboF4OJ1vY2iEGOlJFxY1Xur67ujAbO3+lggfsO40As1iQTjdUMsHvG6SVOZUgajORG1N7/AuiZ/xQg215lnPHkcHfVf2GP9d/VMPtMPBPLJ29ZuroRXnIF+jxjN0cdcg9WiA0QjQQNW+akfekyuJ47nUJatWu8/Vv0j2nBDYF/f83HjvR4X507/cwlDJTfgDk4UGWQ8pl3tLMC+kfXvZD/YEsN9zNVed9oyFxmziHo2ZtzO/2ro=
